const CONSTANCE = {
    OS_ONLOAD: "OS_ONLOAD",
    OS_ONREADY: "OS_ONREADY",
    OS_SHUTDOWN: "OS_SHUTDOWN",
    OS_WINDOW_PANEL_TOGGLE: "OS_WINDOW_PANEL_TOGGLE",
    OS_WINDOW_NEXT: "OS_WINDOW_NEXT",
    OS_WINDOW_PREV: "OS_WINDOW_PREV",
    OS_WINDOW_RELOAD: "OS_WINDOW_RELOAD",
}
export default CONSTANCE